class ConnectionError(Exception): ...

class MPDClient:
    def __init__(self) -> None: ...
    def connect(self, host: str, port: int | None = None) -> None: ...
    def disconnect(self) -> None: ...
    def ping(self) -> None: ...
    def currentsong(self) -> dict[str, str]: ...
    def status(self) -> dict[str, str]: ...
    def add(self, uri: str) -> None: ...
    def play(self, pos: int = 0) -> None: ...
    def clear(self) -> None: ...
    def delete(self, pos: int) -> None: ...
    def load(self, name: str) -> None: ...
    def listplaylists(self) -> list[dict[str, str]]: ...
    def listplaylist(self, name: str) -> list[str]: ...
    def search(self, type: str, query: str) -> list[dict[str, str]]: ...
    def update(self) -> None: ...
