class FFCueSplitter:
    audiotracks: list[dict[str, object]]

    def __init__(self, **kwargs: object) -> None: ...
    def open_cuefile(self) -> list[dict[str, object]]: ...
    def commandargs(self, audiotracks: list | tuple) -> dict[str, list]: ...
    def command_runner(self, arg: str, secs: float) -> list[str] | None: ...
